/* Lesson loading. Built-in lessons ship as static JSON; imported articles live in IndexedDB. */

import { db } from './db.js';

let indexCache = null;
const lessonCache = new Map();

export const LEVELS = [
  { n: 1, label: 'L1 入門',  desc: '短句、現在式、最常用字' },
  { n: 2, label: 'L2 基礎',  desc: '過去/未來式、日常情境' },
  { n: 3, label: 'L3 進階',  desc: '自然語速、片語動詞' },
  { n: 4, label: 'L4 流利',  desc: '慣用語、觀點表達' },
  { n: 5, label: 'L5 母語',  desc: '原速、修辭與細膩語氣' },
];

export const TOPICS = {
  daily:   '日常',
  work:    '職場',
  travel:  '旅遊',
  media:   '媒體',
  science: '科普',
  custom:  '我的文章',
};

/** Built-in lesson index, generated by tools/build-index.mjs. */
export async function loadIndex() {
  if (indexCache) return indexCache;
  try {
    const res = await fetch('./content/index.json', { cache: 'no-cache' });
    indexCache = res.ok ? (await res.json()).lessons || [] : [];
  } catch {
    indexCache = [];
  }
  return indexCache;
}

/** Every lesson available: built-in + imported, imported first. */
export async function allLessons() {
  const [built, mine] = await Promise.all([loadIndex(), db.all('lessons')]);
  const summaries = mine.map(l => ({
    id: l.id, title: l.title, titleZh: l.titleZh || '', level: l.level,
    type: l.type, topic: l.topic || 'custom', count: l.sentences.length,
    summaryZh: l.summaryZh || '', custom: true, at: l.at || 0,
  }));
  summaries.sort((a, b) => b.at - a.at);
  return [...summaries, ...built];
}

export async function getLesson(id) {
  if (lessonCache.has(id)) return lessonCache.get(id);

  const mine = await db.get('lessons', id);
  if (mine) { lessonCache.set(id, mine); return mine; }

  const res = await fetch(`./content/lessons/${encodeURIComponent(id)}.json`, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`找不到課程 ${id}`);
  const lesson = await res.json();
  lessonCache.set(id, lesson);
  return lesson;
}

export async function saveUserLesson(lesson) {
  lessonCache.delete(lesson.id);
  await db.put('lessons', { ...lesson, at: lesson.at || Date.now() });
}

export async function deleteUserLesson(id) {
  lessonCache.delete(id);
  await db.del('lessons', id);
}

/* ---------- difficulty ---------- */

/* The 300 most frequent English words. A sentence built only from these is L1;
   the further it drifts, the higher the level. Cheap, deterministic, offline. */
const COMMON = new Set(`the be to of and a in that have i it for not on with he as you do at this
but his by from they we say her she or an will my one all would there their what so up out if about
who get which go me when make can like time no just him know take people into year your good some
could them see other than then now look only come its over think also back after use two how our
work first well way even new want because any these give day most us is are was were been has had
did does going got am very much many little own right still where why here too more thing man world
life hand part child eye woman place week case point government company number group problem fact
be able need feel seem let put mean keep begin help talk turn start show hear play run move live
believe bring happen write sit stand lose pay meet include continue set learn change lead understand
watch follow stop create speak read allow add spend grow open walk win offer remember love consider
appear buy wait serve die send expect build stay fall cut reach kill remain today tomorrow yesterday
morning night hello hi yes ok okay thanks thank please sorry really actually maybe sure great nice
old long high small large next early young important few public bad same able every another last
great big different such best better free`.split(/\s+/).filter(Boolean));

/** 1–5, from sentence length and how far vocabulary strays from the common core. */
export function scoreDifficulty(sentences) {
  const texts = sentences.map(s => (typeof s === 'string' ? s : s.text));
  if (!texts.length) return 1;

  let words = 0, rare = 0;
  for (const t of texts) {
    for (const w of t.toLowerCase().match(/[a-z']+/g) || []) {
      words++;
      if (!COMMON.has(w.replace(/'(s|t|re|ve|ll|d|m)$/, ''))) rare++;
    }
  }
  const avgLen = words / texts.length;
  const rareRatio = words ? rare / words : 0;

  // Roughly: 9-word common-vocabulary sentences → 1; 24-word rare-heavy → 5.
  const lenScore  = Math.min(5, Math.max(1, (avgLen - 6) / 3.6));
  const vocabScore = Math.min(5, Math.max(1, rareRatio / 0.11));
  return Math.max(1, Math.min(5, Math.round(lenScore * 0.55 + vocabScore * 0.45)));
}

/** Words-per-minute a sentence should be read at, given its level. */
export function wpmFor(level) {
  return [0, 100, 115, 130, 145, 160][level] || 130;
}

/** TTS rate multiplier so a level's audio lands near its target WPM. */
export function rateFor(level) {
  return Math.round((wpmFor(level) / 150) * 100) / 100;
}
