/* Lesson loading. Built-in lessons ship as static JSON; imported articles live in IndexedDB. */

import { db } from "./db.js";
import { scoreDifficulty, wpmFor, rateFor } from "./difficulty.js";

// Re-exported so views can keep importing these from content.js.
export { scoreDifficulty, wpmFor, rateFor };

let indexCache = null;
const lessonCache = new Map();

export const LEVELS = [
  { n: 1, label: "L1 入門", desc: "短句、現在式、最常用字" },
  { n: 2, label: "L2 基礎", desc: "過去/未來式、日常情境" },
  { n: 3, label: "L3 進階", desc: "自然語速、片語動詞" },
  { n: 4, label: "L4 流利", desc: "慣用語、觀點表達" },
  { n: 5, label: "L5 母語", desc: "原速、修辭與細膩語氣" },
];

export const TOPICS = {
  daily: "日常",
  work: "職場",
  travel: "旅遊",
  media: "媒體",
  science: "科普",
  custom: "我的文章",
};

/** Built-in lesson index, generated by tools/build-index.mjs. */
export async function loadIndex() {
  if (indexCache) return indexCache;
  try {
    const res = await fetch("./content/index.json", { cache: "no-cache" });
    indexCache = res.ok ? (await res.json()).lessons || [] : [];
  } catch {
    indexCache = [];
  }
  return indexCache;
}

/** Every lesson available: built-in + imported, imported first. */
export async function allLessons() {
  const [built, mine] = await Promise.all([loadIndex(), db.all("lessons")]);
  const summaries = mine.map((l) => ({
    id: l.id,
    title: l.title,
    titleZh: l.titleZh || "",
    level: l.level,
    type: l.type,
    topic: l.topic || "custom",
    count: l.sentences.length,
    summaryZh: l.summaryZh || "",
    realAudio: !!l.realAudio,
    custom: true,
    at: l.at || 0,
  }));
  summaries.sort((a, b) => b.at - a.at);
  return [...summaries, ...built];
}

export async function getLesson(id) {
  if (lessonCache.has(id)) return lessonCache.get(id);

  const mine = await db.get("lessons", id);
  if (mine) {
    lessonCache.set(id, mine);
    return mine;
  }

  const res = await fetch(`./content/lessons/${encodeURIComponent(id)}.json`, {
    cache: "no-cache",
  });
  if (!res.ok) throw new Error(`找不到課程 ${id}`);
  const lesson = await res.json();
  lessonCache.set(id, lesson);
  return lesson;
}

export async function saveUserLesson(lesson) {
  lessonCache.delete(lesson.id);
  await db.put("lessons", { ...lesson, at: lesson.at || Date.now() });
}

export async function deleteUserLesson(id) {
  lessonCache.delete(id);
  await db.del("lessons", id);
}
